{{- if .Values.cronjob.create }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "DOCUMENTER.fullname" . }}
  labels:
    {{- include "DOCUMENTER.labels" . | nindent 4 }}
spec:
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            {{- with .Values.cronjob.command }}
            command:
              {{- toYaml . | nindent 14 }}
            {{ end }}
            {{- with .Values.cronjob.args }}
            args:
              {{- toYaml . | nindent 14 }}
            {{ end }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            name: {{ include "DOCUMENTER.fullname" . }}
            resources:
              {{- toYaml .Values.resources | nindent 14 }}
            envFrom:
              - configMapRef:
                  name: {{ include "DOCUMENTER.fullname" . }}
            {{- if not (empty .Values.env) }}
            env:
              {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          terminationGracePeriodSeconds: {{ .Values.cronjob.terminationGracePeriodSeconds }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
          {{- toYaml . | nindent 10 }}
          {{- end }}
  schedule: {{ .Values.cronjob.schedule }}
  startingDeadlineSeconds: {{ .Values.cronjob.startingDeadlineSeconds }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  suspend: {{ .Values.cronjob.suspend }}
{{- end }}