apiVersion: v1
kind: Service
metadata:
  name: {{ include "DOCUMENTER.fullname" . }}
  labels:
    {{- include "DOCUMENTER.labels" . | nindent 4 }}
  {{- range $key,$val := .Values.service.labels }}
    {{ $key }}: {{ $val | quote }}
  {{- end }}
spec:
  {{- if eq .Values.service.headless true }}
  clusterIP: None
  {{- end}}
  ports:
  {{- range .Values.service.ports }}
  - port: {{ .port }}
    name: {{ .name }}
    targetPort: {{ .targetPort }}
    protocol: {{ .protocol }}
  {{- end }}
  selector:
    {{- include "DOCUMENTER.selectorLabels" . | nindent 4 }}
